apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: model-serving
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  ingressClassName: "nginx"
  rules:
    - host: detect-sleep-state.com
      http:
        paths:
        - path: /docs
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 8000

        - path: /openapi.json
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 8000

        - path: /healthcheck
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 8000

        - path: /detect_sleep_state
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 8000