services:
  s3:
    image: minio/minio
    container_name: mlflow-minio
    volumes:
      - ./src/database/minio_data:/data ## NOTE: Why can't I use env_file???
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=${MINIO_ADDRESS}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_STORAGE_USE_HTTPS=${MINIO_STORAGE_USE_HTTPS}
      - MINIO_CONSOLE_ADDRESS=${MINIO_CONSOLE_ADDRESS}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${LOCAL_MLFLOW_SERVER_HOST}:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always