services:
  detect-sleep-state:
    image: dattruong1311/dss-api:latest
    platform: linux/amd64
    container_name: dss-container
    build:
      context: .
      dockerfile: ./docker/dockerfile.app
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    init: true