# -------------- Logging ----------
logging_file: ./logs/logging_file.log

# ------------- Hyperparamters ------------
hyperparameters:
  n_estimators: 200         
  min_samples_leaf: 300        
  random_state: 67           
  n_jobs: -1      
training_data: ./data/processed/merged_data.parquet



# -------------- MLflow --------------
experiment_name: dss-training

# -------------- Docker --------------
image_name: dattruong1311/dss-api:latest